# Generated by Django 3.1.2 on 2020-11-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date_create', models.DateTimeField()),
                ('date_modification', models.DateTimeField()),
                ('published', models.BooleanField(null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articlesapp.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesapp.category')),
            ],
        ),
    ]
