# Generated by Django 3.1.2 on 2020-11-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
