# Generated by Django 3.1.2 on 2020-11-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0002_auto_20201117_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
