# Generated by Django 3.1.2 on 2020-11-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0003_auto_20201117_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='articleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articlesapp.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
