# Generated by Django 3.1.2 on 2020-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0005_auto_20201122_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
